apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: trainer
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: trainer
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
