apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: trainer
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mysecretpassword
  POSTGRES_DB: gym_trainer_db #postgres
  DB_HOST: postgres-service
  DB_PORT: "5432"
